<?php
/* -------------------------------------------------------------------------
 * stoneChat / tests/smoke/lib.php
 *
 * Common helpers for the smoke test suite. Sourced from every
 * test_*.php and from run.php.
 *
 *   sc_test_init()              one-time setup (paths, defaults)
 *   sc_test_swap_conf()         back up the real CONF.ini and install
 *                               a test-friendly one with a real
 *                               password and a single mock provider
 *   sc_test_restore_conf()      undo sc_test_swap_conf()
 *   sc_test_start_server()      spawn `php -S` against Pages/router.php
 *   sc_test_stop_server()       kill the spawned php -S
 *   sc_test_wait_server()       poll GET / until a 2xx/3xx comes back
 *
 *   sc_test_http($method, $path, $body) -- issues the request via the
 *                               PHP curl extension, returns an
 *                               associative array with 'status',
 *                               'body', and 'headers'. The cookie jar
 *                               at $GLOBALS['SC_COOKIE_JAR'] is read
 *                               and written automatically.
 *
 *   sc_test_assert_eq($expected, $actual, $msg)
 *   sc_test_assert_status($expected, $msg)
 *   sc_test_assert_json_field($field, $expected, $msg)
 *   sc_test_extract_json($field) -- read a top-level string field
 *
 *   sc_test_login($password)    posts the login form; stores the
 *                               resulting sc_auth cookie so the
 *                               cookie jar sends it on every
 *                               subsequent request.
 *   sc_test_logout()            posts the logout form; clears the
 *                               stored cookie.
 *
 *   sc_test_report()            print the per-process pass/fail tally
 *
 * Counts live in $GLOBALS['SC_TEST_PASS'] / $GLOBALS['SC_TEST_FAIL'].
 *
 * PHP 5.2 compatible.
 * ------------------------------------------------------------------------- */

if (!defined('SC_TEST_LIB_LOADED')) {
    define('SC_TEST_LIB_LOADED', true);

    $GLOBALS['SC_TEST_DIR']     = dirname(__FILE__);
    $GLOBALS['SC_PROJECT_DIR']  = realpath($GLOBALS['SC_TEST_DIR'] . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..');
    $GLOBALS['SC_HOST']        = '127.0.0.1';
    $GLOBALS['SC_PORT']        = getenv('SC_PORT') ? (int)getenv('SC_PORT') : 19999;
    $GLOBALS['SC_BASE_URL']    = 'http://' . $GLOBALS['SC_HOST'] . ':' . $GLOBALS['SC_PORT'];
    $GLOBALS['SC_TEST_PASSWORD'] = getenv('SC_TEST_PASSWORD')
        ? getenv('SC_TEST_PASSWORD') : 'smoketest123';

    /* PHP binary: SC_PHP_BIN env var, or $argv[0]'s PHP_BINARY. */
    $GLOBALS['SC_PHP_BIN'] = getenv('SC_PHP_BIN');
    if (!$GLOBALS['SC_PHP_BIN'] && defined('PHP_BINARY')) {
        $GLOBALS['SC_PHP_BIN'] = PHP_BINARY;
    }
    if (!$GLOBALS['SC_PHP_BIN']) {
        fwrite(STDERR, "[FATAL] cannot determine PHP binary\n");
        exit(2);
    }

    $GLOBALS['SC_CA_CERT']    = $GLOBALS['SC_PROJECT_DIR']
        . DIRECTORY_SEPARATOR . 'ModernNetwork' . DIRECTORY_SEPARATOR
        . 'cacert.pem';

    $GLOBALS['SC_COOKIE_JAR'] = tempnam(sys_get_temp_dir(), 'sc_cookies_');
    if ($GLOBALS['SC_COOKIE_JAR'] === false) {
        fwrite(STDERR, "[FATAL] cannot allocate cookie jar\n");
        exit(2);
    }

    $GLOBALS['SC_TEST_PASS']  = 0;
    $GLOBALS['SC_TEST_FAIL']  = 0;
    $GLOBALS['SC_LAST_BODY']  = '';
    $GLOBALS['SC_LAST_STATUS'] = 0;
    $GLOBALS['SC_LAST_HEADERS'] = array();
    $GLOBALS['SC_AUTH_COOKIE'] = '';
    $GLOBALS['SC_SERVER_PROC'] = null;
    $GLOBALS['SC_SERVER_OUT'] = '';
    $GLOBALS['SC_SERVER_ERR'] = '';
    $GLOBALS['SC_MOCK_PROC']  = null;
    $GLOBALS['SC_TEST_INI_PATH'] = $GLOBALS['SC_PROJECT_DIR']
        . DIRECTORY_SEPARATOR . 'CONF.test.ini';
    $GLOBALS['SC_BACKUP_PATH']  = $GLOBALS['SC_PROJECT_DIR']
        . DIRECTORY_SEPARATOR . 'CONF.ini.bak';
    $GLOBALS['SC_REAL_CONF']    = $GLOBALS['SC_PROJECT_DIR']
        . DIRECTORY_SEPARATOR . 'CONF.ini';
}

/* sc_test_write_ini($path)
 *   Write a fresh test-friendly CONF.ini. Idempotent; the caller
 *   decides which path to write to. */
if (!function_exists('sc_test_write_ini')) {
    function sc_test_write_ini($path) {
        $ca   = $GLOBALS['SC_CA_CERT'];
        $stun = $GLOBALS['SC_PHP_BIN'];
        $port = (int)$GLOBALS['SC_PORT'];
        $pw   = $GLOBALS['SC_TEST_PASSWORD'];
        $body = <<<INI
; Auto-generated by tests/smoke. Do not commit.
[server]
port = {$port}

[llm]
api_base = http://127.0.0.1:9998/Server/api/mock_llm.php
api_key = smoketest
model = mock-gpt

[paths]
ca_cert = {$ca}
stunnel = {$stun}

[proxy]
port = 18443

[auth]
max_attempts = 5
lockout_seconds = 300
cookie_name = sc_auth

[User Admin]
password = {$pw}
active = 1
can_edit_config = 1
excluded_models =

[ui]
title = stoneChat
default_lang = en
theme = classic2001

[Model mock]
id = mock
label = Mock Local Provider
type = openai
api_base = http://127.0.0.1:9998/Server/api/mock_llm.php
api_key = mock_key
model = mock-gpt
stream = true
INI;
        $bytes = @file_put_contents($path, $body);
        return ($bytes !== false);
    }
}

/* sc_test_swap_conf()
 *   Back up CONF.ini (if any), write a test-friendly version. */
if (!function_exists('sc_test_swap_conf')) {
    function sc_test_swap_conf() {
        if (is_file($GLOBALS['SC_REAL_CONF'])) {
            @rename($GLOBALS['SC_REAL_CONF'], $GLOBALS['SC_BACKUP_PATH']);
        }
        sc_test_write_ini($GLOBALS['SC_TEST_INI_PATH']);
        @copy($GLOBALS['SC_TEST_INI_PATH'], $GLOBALS['SC_REAL_CONF']);
    }
}

/* sc_test_restore_conf()
 *   Inverse of sc_test_swap_conf. Always called on shutdown. */
if (!function_exists('sc_test_restore_conf')) {
    function sc_test_restore_conf() {
        if (is_file($GLOBALS['SC_REAL_CONF'])) {
            @unlink($GLOBALS['SC_REAL_CONF']);
        }
        if (is_file($GLOBALS['SC_BACKUP_PATH'])) {
            @rename($GLOBALS['SC_BACKUP_PATH'], $GLOBALS['SC_REAL_CONF']);
        }
        if (is_file($GLOBALS['SC_TEST_INI_PATH'])) {
            @unlink($GLOBALS['SC_TEST_INI_PATH']);
        }
        /* Clear any lockout rows written by the tests. */
        $lc = $GLOBALS['SC_PROJECT_DIR']
            . DIRECTORY_SEPARATOR . 'HISTORY'
            . DIRECTORY_SEPARATOR . '.lockout_cache';
        if (is_file($lc)) {
            @unlink($lc);
        }
        @unlink($GLOBALS['SC_COOKIE_JAR']);
    }
}

/* sc_test_start_server($port, $doc_root, $router)
 *   Spawn `php -S host:port` in the background. Returns true on
 *   success. On Windows, uses proc_open with pipes; on Unix, falls
 *   back to shell & redirection. */
if (!function_exists('sc_test_start_server')) {
    function sc_test_start_server($port, $doc_root, $router, $mock = false) {
        $host = $GLOBALS['SC_HOST'];
        $php  = $GLOBALS['SC_PHP_BIN'];

        $cmd = array(
            $php, '-S', $host . ':' . $port,
            '-t', $doc_root,
            $router,
        );
        $descriptors = array(
            0 => array('pipe', 'r'),
            1 => array('pipe', 'w'),
            2 => array('pipe', 'w'),
        );
        $env = array(
            'PATH' => getenv('PATH'),
            'SystemRoot' => getenv('SystemRoot'),
            'TEMP' => getenv('TEMP'),
            'TMP' => getenv('TMP'),
        );
        $proc = @proc_open($cmd, $descriptors, $pipes, $doc_root, $env);
        if (!is_resource($proc)) {
            fwrite(STDERR, "[FATAL] proc_open failed for $cmd[0] $cmd[1]\n");
            return false;
        }
        fclose($pipes[0]);
        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);

        if ($mock) {
            $GLOBALS['SC_MOCK_PROC'] = array($proc, $pipes);
        } else {
            $GLOBALS['SC_SERVER_PROC'] = array($proc, $pipes);
        }
        return true;
    }
}

/* sc_test_stop_server()
 *   Kill whichever background servers the helper owns. Safe to
 *   call multiple times. */
if (!function_exists('sc_test_stop_server')) {
    function sc_test_stop_server() {
        foreach (array('SC_SERVER_PROC', 'SC_MOCK_PROC') as $key) {
            $h = $GLOBALS[$key];
            if (!is_array($h)) { continue; }
            $proc = $h[0];
            $pipes = $h[1];
            if (is_resource($proc)) {
                /* Best-effort: terminate the process tree. */
                $status = @proc_get_status($proc);
                if (!empty($status['pid'])) {
                    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                        @exec('taskkill /F /T /PID ' . (int)$status['pid'] . ' 2>NUL');
                    } else {
                        @exec('kill -9 ' . (int)$status['pid'] . ' 2>/dev/null');
                    }
                }
                foreach ($pipes as $p) {
                    if (is_resource($p)) { @fclose($p); }
                }
                @proc_close($proc);
            }
            $GLOBALS[$key] = null;
        }
    }
}

/* sc_test_wait_server($port, $seconds)
 *   Poll GET / until a 2xx/3xx arrives or the deadline elapses.
 *   Returns the final status, or 0 on failure. */
if (!function_exists('sc_test_wait_server')) {
    function sc_test_wait_server($port, $seconds) {
        $deadline = microtime(true) + $seconds;
        $host = $GLOBALS['SC_HOST'];
        $status = 0;
        while (microtime(true) < $deadline) {
            $fp = @fsockopen($host, $port, $errno, $errstr, 1);
            if ($fp !== false) {
                @stream_set_timeout($fp, 2);
                $req = "GET / HTTP/1.0\r\nHost: $host\r\nConnection: close\r\n\r\n";
                @fwrite($fp, $req);
                $line = '';
                while (!@feof($fp)) {
                    $buf = @fgets($fp, 1024);
                    if ($buf === false) { break; }
                    $line .= $buf;
                    if (preg_match('#^HTTP/\S+\s+(\d+)#', $line, $m)) {
                        $status = (int)$m[1];
                        break;
                    }
                }
                @fclose($fp);
            }
            if ($status >= 200 && $status < 400) {
                return $status;
            }
            usleep(100000);
        }
        return $status;
    }
}

/* sc_test_http($method, $path, $body, $extra_headers)
 *   Issue an HTTP request to the test server using fsockopen.
 *   Cookies are persisted in $GLOBALS['SC_COOKIE_JAR'] (Netscape
 *   format) so subsequent calls re-use the session cookie. The
 *   response body is stored in $GLOBALS['SC_LAST_BODY'], status
 *   in $GLOBALS['SC_LAST_STATUS'], headers in
 *   $GLOBALS['SC_LAST_HEADERS']. */
if (!function_exists('sc_test_http')) {
    function sc_test_http($method, $path, $body = '', $extra_headers = array()) {
        $host  = $GLOBALS['SC_HOST'];
        $port  = $GLOBALS['SC_PORT'];
        $body_str = ($body === null) ? '' : (string)$body;

        /* Collect cookies to send. The cookie jar is the source
         * of truth; we just merge with $GLOBALS['SC_AUTH_COOKIE']
         * (which is a session cookie set during login). */
        $cookies = sc_test_collect_cookies();
        $headers = array();
        if (count($cookies) > 0) {
            $headers[] = 'Cookie: ' . implode('; ', $cookies);
        }
        $headers[] = 'Accept: application/json';
        if ($body_str !== '') {
            $headers[] = 'Content-Type: application/json';
        }
        $headers[] = 'Content-Length: ' . strlen($body_str);
        $headers[] = 'Connection: close';
        foreach ($extra_headers as $h) {
            $headers[] = $h;
        }

        $req  = strtoupper($method) . ' ' . $path . " HTTP/1.1\r\n";
        $req .= 'Host: ' . $host . "\r\n";
        foreach ($headers as $h) {
            $req .= $h . "\r\n";
        }
        $req .= "\r\n" . $body_str;

        $errno = 0;
        $errstr = '';
        $fp = @fsockopen($host, $port, $errno, $errstr, 10);
        if ($fp === false) {
            $GLOBALS['SC_LAST_BODY'] = '';
            $GLOBALS['SC_LAST_STATUS'] = 0;
            $GLOBALS['SC_LAST_HEADERS'] = array();
            return 0;
        }
        @stream_set_timeout($fp, 30);
        @fwrite($fp, $req);
        $raw = '';
        while (!@feof($fp)) {
            $chunk = @fread($fp, 8192);
            if ($chunk === false || $chunk === '') { break; }
            $raw .= $chunk;
        }
        @fclose($fp);

        $sep = strpos($raw, "\r\n\r\n");
        if ($sep === false) {
            $GLOBALS['SC_LAST_BODY'] = $raw;
            $GLOBALS['SC_LAST_STATUS'] = 0;
            $GLOBALS['SC_LAST_HEADERS'] = array();
            return 0;
        }
        $head_block = substr($raw, 0, $sep);
        $body_out   = substr($raw, $sep + 4);
        $status = 0;
        $first  = strtok($head_block, "\r\n");
        if (preg_match('#^HTTP/\S+\s+(\d+)#', $first, $m)) {
            $status = (int)$m[1];
        }
        $GLOBALS['SC_LAST_HEADERS'] = array();
        $set_cookies = array();
        foreach (preg_split("/\r\n/", $head_block) as $line) {
            $colon = strpos($line, ':');
            if ($colon === false) { continue; }
            $k = trim(substr($line, 0, $colon));
            $v = trim(substr($line, $colon + 1));
            $lk = strtolower($k);
            if ($lk === 'set-cookie') {
                $set_cookies[] = $v;
            } else {
                $GLOBALS['SC_LAST_HEADERS'][$k] = $v;
            }
        }
        /* Append any new Set-Cookie headers to the jar. */
        if (count($set_cookies) > 0) {
            sc_test_store_cookies($set_cookies, $host, $path);
        }
        $GLOBALS['SC_LAST_BODY'] = $body_out;
        $GLOBALS['SC_LAST_STATUS'] = $status;
        return $status;
    }
}

/* sc_test_collect_cookies()
 *   Read the Netscape cookie jar and return a list of "name=value"
 *   pairs (one per cookie, skipping expired or non-matching hosts).
 *   We intentionally keep this simple: a real cookie domain match
 *   is unnecessary for our single-host tests. */
if (!function_exists('sc_test_collect_cookies')) {
    function sc_test_collect_cookies() {
        $out = array();
        $path = $GLOBALS['SC_COOKIE_JAR'];
        if (!is_file($path) || !is_readable($path)) { return $out; }
        $lines = @file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if (!is_array($lines)) { return $out; }
        foreach ($lines as $line) {
            if (substr($line, 0, 1) === '#') { continue; }
            $parts = explode("\t", $line);
            if (count($parts) < 7) { continue; }
            $name = $parts[5];
            $val  = $parts[6];
            /* Skip expired cookies: field 4 is the expiry unix time;
             * 0 means session cookie. */
            $exp = (int)$parts[4];
            if ($exp > 0 && $exp < time()) { continue; }
            $out[] = $name . '=' . $val;
        }
        return $out;
    }
}

/* sc_test_store_cookies($set_cookie_values, $host, $request_path)
 *   Parse one or more Set-Cookie header values and append them to
 *   the Netscape jar, replacing any existing entry with the same
 *   name. */
if (!function_exists('sc_test_store_cookies')) {
    function sc_test_store_cookies($set_cookie_values, $host, $request_path) {
        $path = $GLOBALS['SC_COOKIE_JAR'];
        $existing = array();
        $lines = array();
        if (is_file($path) && is_readable($path)) {
            $raw_lines = @file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            if (is_array($raw_lines)) {
                foreach ($raw_lines as $ln) {
                    if (substr($ln, 0, 1) === '#') {
                        $lines[] = $ln;
                        continue;
                    }
                    $parts = explode("\t", $ln);
                    if (count($parts) >= 7) {
                        $existing[$parts[5]] = $ln;
                    } else {
                        $lines[] = $ln;
                    }
                }
            }
        }
        foreach ($set_cookie_values as $sc) {
            $kv = explode(';', $sc, 2);
            $name_val = trim($kv[0]);
            $eq = strpos($name_val, '=');
            if ($eq === false) { continue; }
            $cname = substr($name_val, 0, $eq);
            $cval  = substr($name_val, $eq + 1);

            $expires = 0;
            $path_attr = '/';
            $secure = 'FALSE';
            foreach (array_slice(explode(';', $sc), 1) as $attr) {
                $attr = trim($attr);
                $aeq = strpos($attr, '=');
                if ($aeq === false) { continue; }
                $ak = strtolower(trim(substr($attr, 0, $aeq)));
                $av = trim(substr($attr, $aeq + 1));
                if ($ak === 'expires') {
                    $ts = strtotime($av);
                    if ($ts !== false) { $expires = $ts; }
                } elseif ($ak === 'path') {
                    $path_attr = $av;
                } elseif ($ak === 'secure') {
                    $secure = 'TRUE';
                }
            }
            $line = implode("\t", array(
                $host,           /* domain */
                'FALSE',         /* host-only flag */
                $path_attr,      /* path */
                $secure,         /* secure */
                $expires,        /* expiry */
                $cname,          /* name */
                $cval,           /* value */
            ));
            $existing[$cname] = $line;
        }
        $lines = array('# Netscape HTTP Cookie File');
        foreach ($existing as $ln) { $lines[] = $ln; }
        @file_put_contents($path, implode("\n", $lines) . "\n");
    }
}

/* sc_test_assert_eq($expected, $actual, $message)
 *   Compare two strings; bump the pass/fail counter. */
if (!function_exists('sc_test_assert_eq')) {
    function sc_test_assert_eq($expected, $actual, $message) {
        if ((string)$expected === (string)$actual) {
            echo "  [ OK ] $message\n";
            $GLOBALS['SC_TEST_PASS']++;
        } else {
            echo "  [FAIL] $message\n";
            echo "         expected: " . var_export($expected, true) . "\n";
            echo "         actual:   " . var_export($actual, true) . "\n";
            $GLOBALS['SC_TEST_FAIL']++;
        }
    }
}

/* sc_test_assert_status($expected, $message) */
if (!function_exists('sc_test_assert_status')) {
    function sc_test_assert_status($expected, $message) {
        sc_test_assert_eq((string)$expected, (string)$GLOBALS['SC_LAST_STATUS'],
            $message . ' (HTTP status)');
    }
}

/* sc_test_assert_json_field($field, $expected, $message) */
if (!function_exists('sc_test_assert_json_field')) {
    function sc_test_assert_json_field($field, $expected, $message) {
        $actual = sc_test_extract_json($field);
        sc_test_assert_eq((string)$expected, (string)$actual, $message);
    }
}

/* sc_test_extract_json($field)
 *   Read a top-level string field from the last response body. */
if (!function_exists('sc_test_extract_json')) {
    function sc_test_extract_json($field) {
        $body = $GLOBALS['SC_LAST_BODY'];
        if (!is_string($body) || $body === '') { return ''; }
        $obj = json_decode($body, true);
        if (!is_array($obj) || !array_key_exists($field, $obj)) { return ''; }
        $v = $obj[$field];
        if (is_bool($v)) { return $v ? 'true' : 'false'; }
        if (is_null($v)) { return 'null'; }
        return (string)$v;
    }
}

/* sc_test_login($password)
 *   POST /Server/api/auth.php with the login form, then read the
 *   sc_auth cookie out of the jar. Subsequent calls to sc_test_http
 *   include it as a Cookie header. */
if (!function_exists('sc_test_login')) {
    function sc_test_login($password = null) {
        if ($password === null) {
            $password = $GLOBALS['SC_TEST_PASSWORD'];
        }
        $body = json_encode(array(
            'action' => 'login',
            'password' => $password,
        ));
        $status = sc_test_http('POST', '/Server/api/auth.php', $body);
        $GLOBALS['SC_AUTH_COOKIE'] = sc_test_read_cookie('sc_auth');
        return $status;
    }
}

/* sc_test_logout() */
if (!function_exists('sc_test_logout')) {
    function sc_test_logout() {
        $body = json_encode(array('action' => 'logout'));
        $status = sc_test_http('POST', '/Server/api/auth.php', $body);
        $GLOBALS['SC_AUTH_COOKIE'] = '';
        return $status;
    }
}

/* sc_test_read_cookie($name)
 *   Parse a Netscape cookie jar and return the value of $name. */
if (!function_exists('sc_test_read_cookie')) {
    function sc_test_read_cookie($name) {
        $path = $GLOBALS['SC_COOKIE_JAR'];
        if (!is_file($path) || !is_readable($path)) { return ''; }
        $lines = @file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if (!is_array($lines)) { return ''; }
        foreach ($lines as $line) {
            if (substr($line, 0, 1) === '#') { continue; }
            $parts = explode("\t", $line);
            if (count($parts) >= 7 && $parts[5] === $name) {
                return $parts[6];
            }
        }
        return '';
    }
}

/* sc_test_report()
 *   Print the per-process pass/fail tally. */
if (!function_exists('sc_test_report')) {
    function sc_test_report() {
        echo "\n";
        echo "================================================================\n";
        echo "  PASSED: " . $GLOBALS['SC_TEST_PASS']
            . "    FAILED: " . $GLOBALS['SC_TEST_FAIL'] . "\n";
        echo "================================================================\n";
    }
}

/* sc_test_cleanup_history($chat_id)
 *   Best-effort delete via the API, ignoring the response. */
if (!function_exists('sc_test_cleanup_history')) {
    function sc_test_cleanup_history($chat_id) {
        if (!is_string($chat_id) || $chat_id === '') { return; }
        $auth = $GLOBALS['SC_AUTH_COOKIE'];
        $GLOBALS['SC_AUTH_COOKIE'] = '';
        if ($auth !== '') {
            $GLOBALS['SC_AUTH_COOKIE'] = $auth;
        }
        sc_test_http('DELETE', '/Server/api/history.php?id=' . urlencode($chat_id));
    }
}
