<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => 'Anmelden',
    'login.password' => 'Passwort',
    'login.submit' => 'Anmelden',
    'login.error' => 'Ungültiges Passwort',
    'login.locked' => 'Zu viele Fehlversuche. Bitte später erneut versuchen.',
    'chat.send' => 'Senden',
    'chat.stop' => 'Stoppen',
    'chat.regenerate' => 'Neu generieren',
    'chat.countdown' => 'Automatischer Neustart in {n}s...',
    'chat.connectCheck' => 'Verbindung prüfen',
    'chat.reloadConfig' => 'Konfiguration laden',
    'chat.editConfig' => 'Konfiguration bearbeiten',
    'chat.logout' => 'Abmelden',
    'chat.about' => 'Über',
    'chat.newChat' => 'Neuer Chat',
    'chat.deleteChat' => 'Chat löschen',
    'chat.renameChat' => 'Chat umbenennen',
    'sidebar.history' => 'Verlauf',
    'common.close' => 'Schließen',
    'error.network' => 'Netzwerkfehler',
    'error.timeout' => 'Zeitüberschreitung',
    'error.unauthorized' => 'Nicht autorisiert',
    'role.user' => 'Sie',
    'role.assistant' => 'KI',
    'role.system' => 'System',
);
