<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => 'Login',
    'login.password' => 'Password',
    'login.submit' => 'Sign in',
    'login.error' => 'Invalid password',
    'login.locked' => 'Too many failed attempts. Please wait and try again later.',
    'chat.send' => 'Send',
    'chat.stop' => 'Stop',
    'chat.regenerate' => 'Regenerate',
    'chat.countdown' => 'Auto-retry in {n}s...',
    'chat.connectCheck' => 'Check connection',
    'chat.reloadConfig' => 'Reload config',
    'chat.editConfig' => 'Edit config',
    'chat.logout' => 'Logout',
    'chat.about' => 'About',
    'chat.newChat' => 'New chat',
    'chat.deleteChat' => 'Delete chat',
    'chat.renameChat' => 'Rename chat',
    'sidebar.history' => 'History',
    'common.close' => 'Close',
    'error.network' => 'Network error',
    'error.timeout' => 'Request timeout',
    'error.unauthorized' => 'Unauthorized',
);
