<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => 'Connexion',
    'login.password' => 'Mot de passe',
    'login.submit' => 'Se connecter',
    'login.error' => 'Mot de passe invalide',
    'login.locked' => 'Trop de tentatives échouées. Réessayez plus tard.',
    'chat.send' => 'Envoyer',
    'chat.stop' => 'Arrêter',
    'chat.regenerate' => 'Régénérer',
    'chat.countdown' => 'Nouvelle tentative dans {n}s...',
    'chat.connectCheck' => 'Vérifier la connexion',
    'chat.reloadConfig' => 'Recharger la config',
    'chat.editConfig' => 'Modifier la config',
    'chat.logout' => 'Déconnexion',
    'chat.about' => 'À propos',
    'chat.newChat' => 'Nouvelle discussion',
    'chat.deleteChat' => 'Supprimer la discussion',
    'chat.renameChat' => 'Renommer la discussion',
    'sidebar.history' => 'Historique',
    'common.close' => 'Fermer',
    'error.network' => 'Erreur réseau',
    'error.timeout' => 'Délai dépassé',
    'error.unauthorized' => 'Non autorisé',
    'role.user' => 'Vous',
    'role.assistant' => 'IA',
    'role.system' => 'Système',
);
