<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => 'ログイン',
    'login.password' => 'パスワード',
    'login.submit' => 'サインイン',
    'login.error' => 'パスワードが無効です',
    'login.locked' => 'ログイン失敗が多すぎます。しばらくお待ちください。',
    'chat.send' => '送信',
    'chat.stop' => '停止',
    'chat.regenerate' => '再生成',
    'chat.countdown' => '{n}秒後に自動再試行...',
    'chat.connectCheck' => '接続を確認',
    'chat.reloadConfig' => '設定を再読込',
    'chat.editConfig' => '設定を編集',
    'chat.logout' => 'ログアウト',
    'chat.about' => '情報',
    'chat.newChat' => '新規チャット',
    'chat.deleteChat' => 'チャットを削除',
    'chat.renameChat' => 'チャット名を変更',
    'sidebar.history' => '履歴',
    'common.close' => '閉じる',
    'error.network' => 'ネットワークエラー',
    'error.timeout' => 'リクエストタイムアウト',
    'error.unauthorized' => '認証エラー',
    'role.user' => 'あなた',
    'role.assistant' => 'AI',
    'role.system' => 'システム',
);
