<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => '로그인',
    'login.password' => '비밀번호',
    'login.submit' => '로그인',
    'login.error' => '잘못된 비밀번호',
    'login.locked' => '로그인 실패횟수가 너무 많습니다. 잠시 후 다시 시도해주세요.',
    'chat.send' => '보내기',
    'chat.stop' => '정지',
    'chat.regenerate' => '재생성',
    'chat.countdown' => '{n}초 후 자동 재시도...',
    'chat.connectCheck' => '연결 확인',
    'chat.reloadConfig' => '설정 다시 불러오기',
    'chat.editConfig' => '설정 편집',
    'chat.logout' => '로그아웃',
    'chat.about' => '정보',
    'chat.newChat' => '새 대화',
    'chat.deleteChat' => '대화 삭제',
    'chat.renameChat' => '대화 이름 변경',
    'sidebar.history' => '기록',
    'common.close' => '닫기',
    'error.network' => '네트워크 오류',
    'error.timeout' => '요청 시간 초과',
    'error.unauthorized' => '인증 실패',
    'role.user' => '나',
    'role.assistant' => 'AI',
    'role.system' => '시스템',
);
