<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => 'Вход',
    'login.password' => 'Пароль',
    'login.submit' => 'Войти',
    'login.error' => 'Неверный пароль',
    'login.locked' => 'Слишком много неудачных попыток. Повторите попытку позже.',
    'chat.send' => 'Отправить',
    'chat.stop' => 'Остановить',
    'chat.regenerate' => 'Перегенерировать',
    'chat.countdown' => 'Автоповтор через {n}с...',
    'chat.connectCheck' => 'Проверить соединение',
    'chat.reloadConfig' => 'Перезагрузить конфиг',
    'chat.editConfig' => 'Редактировать конфиг',
    'chat.logout' => 'Выйти',
    'chat.about' => 'О программе',
    'chat.newChat' => 'Новый чат',
    'chat.deleteChat' => 'Удалить чат',
    'chat.renameChat' => 'Переименовать чат',
    'sidebar.history' => 'История',
    'common.close' => 'Закрыть',
    'error.network' => 'Сетевая ошибка',
    'error.timeout' => 'Время истекло',
    'error.unauthorized' => 'Не авторизован',
);
