<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => '登录',
    'login.password' => '密码',
    'login.submit' => '登录',
    'login.error' => '密码错误',
    'login.locked' => '登录尝试次数过多，请稍后再试。',
    'chat.send' => '发送',
    'chat.stop' => '停止',
    'chat.regenerate' => '重新生成',
    'chat.countdown' => '{n} 秒后自动重试...',
    'chat.connectCheck' => '检查连接',
    'chat.reloadConfig' => '重新加载配置',
    'chat.editConfig' => '编辑配置',
    'chat.logout' => '退出',
    'chat.about' => '关于',
    'chat.newChat' => '新建对话',
    'chat.deleteChat' => '删除对话',
    'chat.renameChat' => '重命名对话',
    'sidebar.history' => '历史记录',
    'common.close' => '关闭',
    'error.network' => '网络错误',
    'error.timeout' => '请求超时',
    'error.unauthorized' => '未授权',
    'role.user' => '你',
    'role.assistant' => 'AI',
    'role.system' => '系统',
);
