<?php
return array(
    'app.title' => 'stoneChat',
    'login.title' => '登入',
    'login.password' => '密碼',
    'login.submit' => '登入',
    'login.error' => '密碼錯誤',
    'login.locked' => '登入嘗試次數過多，請稍後再試。',
    'chat.send' => '發送',
    'chat.stop' => '停止',
    'chat.regenerate' => '重新生成',
    'chat.countdown' => '{n} 秒後自動重試...',
    'chat.connectCheck' => '檢查連接',
    'chat.reloadConfig' => '重新載入配置',
    'chat.editConfig' => '編輯配置',
    'chat.logout' => '登出',
    'chat.about' => '關於',
    'chat.newChat' => '新建對話',
    'chat.deleteChat' => '刪除對話',
    'chat.renameChat' => '重命名對話',
    'sidebar.history' => '歷史記錄',
    'common.close' => '關閉',
    'error.network' => '網絡錯誤',
    'error.timeout' => '請求超時',
    'error.unauthorized' => '未授權',
    'role.user' => '你',
    'role.assistant' => 'AI',
    'role.system' => '系統',
);
